# Main Application Configuration
spring:
  application:
    name: timatix-booking-services
    version: 1.0.0

  profiles:
    active: local

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 25
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

  # SQL Initialization
  sql:
    init:
      mode: always
      continue-on-error: false

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  # JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: false
    time-zone: Africa/Johannesburg
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL

  # Validation Configuration
  validation:
    enabled: true

  # Cache Configuration
  cache:
    type: simple
    cache-names: users,vehicles,services,bookings

# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  info:
    env:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

# Logging Configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.timatix.servicebooking: INFO
    org.springframework.web: INFO

# File Storage Configuration
file:
  upload:
    dir: ./uploads
    max-size: 10MB

# Business Configuration
business:
  name: Timatix Auto Works
  address: 123 Workshop Street, Cape Town, South Africa
  phone: +27-21-123-4567
  email: info@timatix.com
  website: https://timatix.com

# Booking Configuration
booking:
  slots:
    default-duration: 60
    max-advance-days: 30
  quotes:
    default-validity-days: 7

# Application Configuration
app:
  timezone: Africa/Johannesburg
  locale: en_ZA